### ISSUE TITLE
go vet errors in render.go

### ISSUE THREAD

**Issue by ixtenu** [japanoise/gomacs#26]
```
% go version
go version go1.17 linux/amd64
% go vet
# github.com/japanoise/gomacs
./render.go:92:27: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
./render.go:124:27: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
```
Using latest commit (81ec99beb0), no local changes.  This problem prevents the tests from being run, since `go test` runs `go vet` and aborts when it fails.

It's not clear to me what these two lines are trying to do.  Both lines are conditioned on `buf.hasMode("gdi")`, but there aren't any other references to `gdi` in the tree.

**Comment by japanoise** [comment]
fixed in cd15ac8db97007ac062dac815b7ac7c5398a6ba5
