### ISSUE TITLE
query-replace-regexp hangs with certain regexps

### ISSUE THREAD

**Issue by ixtenu** [japanoise/gomacs#36]
1. Run `gomacs` (with or without specifying a file, it doesn't matter)
2. `M-x query-replace-regexp`
3. At the `Find regexp:` prompt, input `a*`
4. At the `Replace a* with:` prompt, input `b`
5. At the next prompt, type `!` to replace all occurrences

This hangs `gomacs`.  It pins a CPU and never comes back.  The `a*` matches everything, so it's a weird operation, but I did this by accident and had to `pkill gomacs` to recover.

**Comment by japanoise** [comment]
I think I know what's happening here. It's recursively replacing the empty strings it creates with further empty strings.

"" -> "b" -> "bb" -> "bbb" -> etc.

Looks like it might be a bug in the go regex library, but the workaround I've suggested is acceptable imo.

**Comment by japanoise** [comment]
> Looks like it might be a bug in the go regex library, but the workaround I've suggested is acceptable imo.

Or not: https://go.dev/play/p/Qgb8hvR7Ii4

I still question whether we'd want to do this, though.

**Comment by ixtenu** [comment]
> GNU Emacs allows you to run the footgun with amusing results:

https://github.com/japanoise/gomacs/pull/37 reproduces this behavior in Gomacs.

> I still question whether we'd want to do this, though.

My original thought was Gomacs shouldn't hang from a regexp typo.  I don't know if anyone would try this on purpose.  In GNU Emacs (and my PR), it effectively allows inserting text prior to every rune.  Maybe it could be used to create weird textual effects (like a space between each rune)?

**Comment by japanoise** [comment]
"abcde" -> "a, b, c, d, e" perhaps.

Yeah I can see this being something you might want in an edge case.
