### ISSUE TITLE
Sporadic crash during C-x o

### ISSUE THREAD

**Issue by ixtenu** [japanoise/gomacs#42]
I've seen this crash about a dozen times:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2 pc=0x5722a9]

goroutine 1 [running]:
main.switchWindow()
        /home/username/go/src/github.com/ixtenu/gomacs/window.go:101 +0x29
main.LoadDefaultCommands.func20(0x3)
        /home/username/go/src/github.com/ixtenu/gomacs/commands.go:284 +0x17
main.(*CommandFunc).Run(0xc000738f20, 0xc0004b03e1)
        /home/username/go/src/github.com/ixtenu/gomacs/commands.go:193 +0x36
main.RunCommandForKey({0xc0004b03e1, 0x3}, 0xc000054f10)
        /home/username/go/src/github.com/ixtenu/gomacs/main.go:587 +0x2c5
main.main()
        /home/username/go/src/github.com/ixtenu/gomacs/main.go:758 +0x79d
```

Unfortunately, it's tricky to reproduce.  It always happens during `C-x o` (or shortly afterward) when `gomacs` has multiple windows viewing different files.  It seems to usually occur when `C-x o` immediately follows another windowing operation.  Sometimes, it doesn't crash right away, but the cursor disappears and the next `C-x o` crashes.

Any idea what might be going on here?  I assume the call to `getFocusWindow()`  in `switchWindow()` is returning `nil`, leading to a nil pointer dereference at window.go:101.  Maybe a race condition?  `getFocusWindow()` being called when `winTree.focused` is being moved from one `winTree` to another?

The above crash was with commit 65fb9ab1 (tip of the `master` branch).  I also saw it on the `zygomys` branch (commit 711b1216fd).  The first time I saw it was on February 6th (commit 47f7e1c7ce), before any of the recent changes.  The call stack is substantially the same each time, except for the pointer addresses.

**Comment by japanoise** [comment]
It's that bloody "concurrency magic" commit again, I bet. It doesn't even fix the problem and likely leads to this and #13 as well.

We could probably fix this by putting a lock in or some other concurrency duct-tape, but honestly I'm not sure the pain of dealing with concurrency is worse than the "slow pasting" you get if you paste text into gomacs and it redraws after every character.

**Comment by ixtenu** [comment]
I've figured out a procedure which reproduces this reliably:

```sh
# Open any two files (the contents don't seem to matter); here using empty files a and b
touch a b
gomacs a b
```

Then in Gomacs:

1. `C-x 3` (horizontal split)
2. `C-x o` (switch to right window)
3. `C-x b`, pick file `b` (puts file `b` in right window)
4. `C-x o` (switch back to left window)
5. `C-x 1` (close the right window)
6. `C-x 3` (reopen the right window)
7. `C-x o` (switch to the right window)
8. `C-x b`, pick file `b` again (puts file `b` in right window)
9. `C-x o` (nothing happens, cursor doesn't move to the left window like it should)
10. `C-x o` (doing it a second time crashes Gomacs)

Following those steps, the crash occurs every time.  I've reproduced it on two machines (Linux and FreeBSD), so hopefully the the result will be the same on your machine.  It reproduces on `master` and both of the open PR branches (`no-concun` and `zygomys`).  I imagine that other sequences can lead to the same crash: e.g., I verified that replacing either or both of the `C-x 3` commands with `C-x 2` still results in a crash.

**Comment by japanoise** [comment]
Replicated succesfully. Gonna put some aggressive debugging info in to see if we can't figure out what kind of state it's getting itself in.

**Comment by japanoise** [comment]
Looks like what happens is the focus manages to be in no buffer at all; here's the state of the window tree at step 9:

```
0xc000786810 spl: true hoz: true foc: false buf: 0x0 lt: 0xc000b80de0 rb: 0xc000b80e10
0xc000b80de0 spl: false hoz: false foc: false buf: 0xc000101450 lt: 0x0 rb: 0x0
0xc000b80e10 spl: false hoz: false foc: false buf: 0xc000101ee0 lt: 0x0 rb: 0x0
```

**Comment by japanoise** [comment]
https://gist.github.com/japanoise/5f02ea1210dc327097f97e838fac42de here's a patch that displays the wintree on the screen after draw step, if you want to do some hacking on it yourself. I think the culprit is the switching code, so I'm gonna have a play and see if I can get it to set the focus more aggresively

**Comment by japanoise** [comment]
Aha! I think the problem is with the parents being set. Should have a patch ready in a sec.
