### ISSUE TITLE
`bindkeymode` overwrites other keybindings

### ISSUE THREAD

**Issue by trembel** [japanoise/gomacs#49]
I tried to set major mode specific keybindings for formatting (e.g. the following for C code). On Emacs, I usually set this to the bindings "C-x C-y". However, if I do this here, I can not enter all the other commands, which start with "C-x" (e.g. quit gomacs, open file, ...).
Attached is my config (which closely follows `examples/gofmt.zy`:
```
// Here's a useful example; automatically gofmt Go buffers.
// Watch out though, as this function wipes the undos.
(emacsdefinecmd "c-fmt" filterbuffer "clang-format")
(bindkeymode "c" "C-x C-y" "c-fmt")
(addsavehook "c" "c-fmt")
```

Has this to do with the change to Zygomys?

**Comment by japanoise** [comment]
> Has this to do with the change to Zygomys?

It might, though I doubt it, Zygomys and Glisp are fairly similar once you get past the differing interface. More likely it's an oversight with how the bindings are done (this is very old code I haven't touched in a hot minute).

**Comment by japanoise** [comment]
Ahh, I see the problem. `func (c *CommandList) GetCommand(key string) (*CommandFunc, error) {` blocks waiting for keys, thus slurping the keys. It doesn't find them in that subtree, so it exits out with a failure. Pretty serious problem. I'll have a think about how to fix this.
